import { useEffect, useState } from 'react';
import { Download, ReceiptIndianRupee, WalletCards } from 'lucide-react';
import { api, download } from '../api';
import { EmptyState } from '../components/feedback/EmptyState';
import { AppShell } from '../components/layout/AppShell';
import { SectionTitle } from '../components/ui/SectionTitle';
import { useApp } from '../context/AppContext';
import { formatDate, formatMoney } from '../utils/formatters';

type Fee = { id: string; dueDate: string; title: string; invoiceNo?: string; amount: number; paidAmount: number; outstanding: number; status: string };
type FeeAccount = { fees: Fee[]; summary: { outstanding: number; advanceBalance: number } };

export default function FeesPage() {
  const { child } = useApp();
  const [account, setAccount] = useState<FeeAccount | null>(null);
  const [error, setError] = useState('');
  useEffect(() => {
    if (child) api<FeeAccount>(`/fees/students/${child.id}`).then(setAccount).catch(requestError => setError(requestError.message));
  }, [child?.id]);
  return (
    <AppShell title="Fees & payments" back>
      <section className="fee-hero fee-page"><div><small>TOTAL OUTSTANDING</small><h1>{formatMoney(account?.summary.outstanding || 0)}</h1><p>{account?.summary.advanceBalance ? `${formatMoney(account.summary.advanceBalance)} advance credit available` : 'Student fee account'}</p></div><ReceiptIndianRupee /></section>
      <div className="filter-pills"><button className="active">All</button><button>Pending</button><button>Paid</button></div>
      <SectionTitle title="Fee ledger" />
      {error ? <EmptyState title="Fee account unavailable" text={error} /> : account?.fees.length ? account.fees.map(fee => (
        <article className="fee-card" key={fee.id}><div><small>{formatDate(fee.dueDate)}</small><h3>{fee.title}</h3><p>{fee.invoiceNo}</p></div><div className="fee-amount"><strong>{formatMoney(fee.outstanding)}</strong><b className={`badge ${fee.status.toLowerCase()}`}>{fee.status}</b></div><div className="fee-actions"><span>Billed {formatMoney(fee.amount)} · Paid {formatMoney(fee.paidAmount)}</span><button onClick={() => download(`/fees/${fee.id}/invoice.pdf`, `${fee.invoiceNo || 'invoice'}.pdf`)}><Download /> Invoice</button></div></article>
      )) : <EmptyState icon={WalletCards} title="No fee entries" text="Fees generated by the accounts office will appear here." />}
    </AppShell>
  );
}
