'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowPathIcon, PencilSquareIcon, PlusIcon, XMarkIcon } from '@heroicons/react/24/outline';
import { useAuth } from './auth-provider';

type SchoolClass = { id:string;name:string;section:string };
type Structure = { id:string;name:string;code?:string;category:string;description?:string;className:string;academicYear:string;amount:string;frequency:string;dueDay:number;chargeOnAdmission:boolean;lateFee:string;isActive:boolean };
type BillingStatus = { academicYear:string;period:string;structures:number;invoices:number;students:number;nextAutomaticRun:string };
const money=(value:string|number)=>`₹${Number(value).toLocaleString('en-IN')}`;
const categories=['TUITION','ANNUAL','ADMISSION','DEVELOPMENT','COMPUTER','LAB','LIBRARY','SPORTS','ACTIVITY','TRANSPORT','EXAM','OTHER'];

export function FeeMaster(){
  const {user}=useAuth(); const canEdit=user?.role==='ADMIN';
  const [classes,setClasses]=useState<SchoolClass[]>([]); const [items,setItems]=useState<Structure[]>([]); const [status,setStatus]=useState<BillingStatus|null>(null);
  const [year,setYear]=useState(''); const [editing,setEditing]=useState<Structure|null|undefined>(undefined); const [saving,setSaving]=useState(false); const [running,setRunning]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  const classNames=useMemo(()=>Array.from(new Set(classes.map(item=>item.name))).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),[classes]);
  async function load(){const [classResponse,statusResponse]=await Promise.all([fetch('/api/proxy/classes'),fetch('/api/proxy/fee-billing/status')]);const nextStatus=statusResponse.ok?await statusResponse.json():null;if(classResponse.ok)setClasses(await classResponse.json());if(nextStatus){setStatus(nextStatus);setYear(value=>value||nextStatus.academicYear);const response=await fetch(`/api/proxy/fee-structures?all=true&academicYear=${nextStatus.academicYear}`);if(response.ok)setItems(await response.json());}}
  async function loadYear(value:string){setYear(value);const response=await fetch(`/api/proxy/fee-structures?all=true&academicYear=${value}`);if(response.ok)setItems(await response.json());}
  useEffect(()=>{void load();},[]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError('');const form=new FormData(event.currentTarget);const body={name:form.get('name'),code:form.get('code')||undefined,category:form.get('category'),description:form.get('description')||undefined,className:form.get('className'),academicYear:form.get('academicYear'),amount:form.get('amount'),frequency:form.get('frequency'),dueDay:form.get('dueDay'),chargeOnAdmission:form.get('chargeOnAdmission')==='on',lateFee:form.get('lateFee')||0,isActive:true};const response=await fetch(editing?.id?`/api/proxy/fee-structures/${editing.id}`:'/api/proxy/fee-structures',{method:editing?.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok){setError(data.message||'Fee head could not be saved.');setSaving(false);return;}setSaving(false);setEditing(undefined);await loadYear(year);}
  async function deactivate(id:string){await fetch(`/api/proxy/fee-structures/${id}`,{method:'DELETE'});await loadYear(year);}
  async function runBilling(){setRunning(true);setMessage('');const response=await fetch('/api/proxy/fee-billing/run',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const data=await response.json().catch(()=>({}));setRunning(false);if(response.ok){setMessage(`Billing complete: ${data.invoices} applicable invoices checked for ${data.students} students. Duplicate invoices were skipped.`);await load();}else setMessage(data.message||'Billing run failed.');}
  const grouped=classNames.map(name=>({name,items:items.filter(item=>item.className===name)}));
  return <><section className="billingRun panel"><div><h2>Monthly billing engine</h2><p>Current period {status?.period||'—'} · Academic year {status?.academicYear||'—'} · {status?.students||0} enrolled students</p></div><dl><div><dt>Active fee heads</dt><dd>{status?.structures||0}</dd></div><div><dt>Invoices this month</dt><dd>{status?.invoices||0}</dd></div><div><dt>Automatic schedule</dt><dd>1st of every month</dd></div></dl><button onClick={()=>void runBilling()} disabled={running}><ArrowPathIcon/>{running?'Running…':'Run billing now'}</button></section>{message&&<div className="billingMessage">{message}</div>}
  <div className="masterToolbar"><div><h2>Class fee master</h2><p>CBSE-aligned configurable fee heads, subject to applicable State/UT rules and management approval.</p></div><label>Academic year<input value={year} onChange={event=>void loadYear(event.target.value)} placeholder="2026-27"/></label>{canEdit&&<button className="primary" onClick={()=>setEditing(null)}><PlusIcon/>Add fee head</button>}</div>
  <div className="feeMasterGrid">{grouped.map(group=><section className="panel classFeeCard" key={group.name}><header><div><h3>{group.name}</h3><p>{group.items.length} configured fee heads</p></div><strong>{money(group.items.reduce((sum,item)=>sum+(item.frequency==='MONTHLY'?Number(item.amount)*12:Number(item.amount)),0))}<small>indicative annual</small></strong></header>{group.items.length?<div>{group.items.map(item=><article key={item.id} className={!item.isActive?'inactive':''}><span><strong>{item.name}</strong><small>{item.category} · {item.frequency.replace('_',' ')} · Due day {item.dueDay}{item.chargeOnAdmission?' · starts on admission':''}</small></span><strong>{money(item.amount)}</strong>{canEdit&&<div><button aria-label={`Edit ${item.name}`} onClick={()=>setEditing(item)}><PencilSquareIcon/></button><button onClick={()=>void deactivate(item.id)}>Deactivate</button></div>}</article>)}</div>:<p className="masterEmpty">No fee breakup configured for this class.</p>}</section>)}</div>
  {editing!==undefined&&<div className="dialogBackdrop" onMouseDown={()=>setEditing(undefined)}><div className="facilityDialog feeMasterDialog" role="dialog" aria-modal="true" onMouseDown={event=>event.stopPropagation()}><div className="dialogTitle"><div><h2>{editing?'Edit fee head':'Add fee head'}</h2><p>Amounts remain configurable because fee heads and revisions must follow the applicable State/UT rules.</p></div><button onClick={()=>setEditing(undefined)} aria-label="Close"><XMarkIcon/></button></div><form className="facilityForm" onSubmit={save}><div className="formColumns"><label>Class<select name="className" defaultValue={editing?.className} required><option value="">Select class</option>{classNames.map(name=><option key={name}>{name}</option>)}</select></label><label>Academic year<input name="academicYear" defaultValue={editing?.academicYear||year} required pattern="\d{4}-\d{2}"/></label></div><div className="formColumns"><label>Fee head<input name="name" defaultValue={editing?.name} required placeholder="Tuition fee"/></label><label>Code<input name="code" defaultValue={editing?.code} placeholder="TUI"/></label></div><div className="formColumns"><label>Category<select name="category" defaultValue={editing?.category||'TUITION'}>{categories.map(value=><option key={value}>{value}</option>)}</select></label><label>Frequency<select name="frequency" defaultValue={editing?.frequency||'MONTHLY'}><option>MONTHLY</option><option>QUARTERLY</option><option>ANNUAL</option><option>ONE_TIME</option></select></label></div><div className="formColumns"><label>Amount<input name="amount" type="number" min=".01" step=".01" defaultValue={editing?.amount} required/></label><label>Due day<input name="dueDay" type="number" min="1" max="28" defaultValue={editing?.dueDay||10} required/></label></div><div className="formColumns"><label>Late fee<input name="lateFee" type="number" min="0" step=".01" defaultValue={editing?.lateFee||0}/></label><label className="checkboxLabel"><input name="chargeOnAdmission" type="checkbox" defaultChecked={editing?.chargeOnAdmission??true}/>Start when student joins/selects class</label></div><label>Description<textarea name="description" rows={2} defaultValue={editing?.description}/></label>{error&&<div className="loginError">{error}</div>}<div className="dialogButtons"><button type="button" onClick={()=>setEditing(undefined)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Save fee head'}</button></div></form></div></div>}</>;
}
