import {
  AcademicCapIcon, BanknotesIcon, BellAlertIcon, BookOpenIcon, BuildingLibraryIcon,
  BuildingOfficeIcon, CalendarDaysIcon, ChartBarSquareIcon, ChatBubbleLeftRightIcon,
  ClipboardDocumentCheckIcon, ClipboardDocumentListIcon, DocumentChartBarIcon,
  DocumentTextIcon, HomeIcon, IdentificationIcon, RectangleStackIcon, UserGroupIcon,
  TruckIcon, UserPlusIcon, UsersIcon,
} from '@heroicons/react/24/outline';

export const icons = {
  Overview: HomeIcon,
  Students: UserGroupIcon,
  Teachers: UsersIcon,
  Classes: AcademicCapIcon,
  Attendance: ClipboardDocumentCheckIcon,
  Fees: BanknotesIcon,
  Exams: IdentificationIcon,
  Admissions: UserPlusIcon,
  HR: BuildingOfficeIcon,
  Academics: RectangleStackIcon,
  Gradebook: DocumentChartBarIcon,
  Lessons: BookOpenIcon,
  Assignments: ClipboardDocumentListIcon,
  Timetable: CalendarDaysIcon,
  Communication: ChatBubbleLeftRightIcon,
  Finance: BanknotesIcon,
  Payroll: DocumentTextIcon,
  Reports: ChartBarSquareIcon,
  Library: BuildingLibraryIcon,
  Events: BellAlertIcon,
  Children: UsersIcon,
  Progress: DocumentChartBarIcon,
  Clubs: UserGroupIcon,
  Audit: DocumentTextIcon,
  'Staff Attendance': ClipboardDocumentCheckIcon,
  'Student Leave': CalendarDaysIcon,
  Transport: TruckIcon,
};
