'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeftIcon, DocumentArrowDownIcon } from '@heroicons/react/24/outline';

type Account = { admissionNo:string;firstName:string;lastName:string;class?:{name:string;section:string};summary:{billed:number;collected:number;concessions:number;outstanding:number;advanceBalance:number};ledgerEntries:{id:string;amount:string;description:string;referenceId?:string;occurredAt:string}[];fees:{id:string;invoiceNo?:string;title:string;amount:string;paidAmount:string;outstanding:number;dueDate:string;status:string;payments:{id:string;receiptNo:string;amount:string;method:string;paidAt:string}[]}[] };
export function StudentFeeAccount({studentId}:{studentId:string}){
  const [account,setAccount]=useState<Account|null>(null);
  useEffect(()=>{fetch(`/api/proxy/fees/students/${studentId}`,{cache:'no-store'}).then(response=>response.ok?response.json():null).then(setAccount);},[studentId]);
  if(!account)return <div className="profileLoading">Loading fee account…</div>;
  return <><div className="profileBack"><Link href="/fees"><ArrowLeftIcon/>Back to fees</Link></div><div className="pageHead feeAccountHead"><div><span className="mono">{account.admissionNo}</span><h1>{account.firstName} {account.lastName}</h1><p>{account.class?`${account.class.name}${account.class.section?`-${account.class.section}`:''}`:'Unassigned'} · Complete fee ledger</p></div></div><div className="feeSummary four"><div><span>Total billed</span><strong>₹{account.summary.billed.toLocaleString('en-IN')}</strong></div><div><span>Collected against invoices</span><strong className="greenText">₹{account.summary.collected.toLocaleString('en-IN')}</strong></div><div><span>Advance credit</span><strong className="blueText">₹{account.summary.advanceBalance.toLocaleString('en-IN')}</strong></div><div><span>Outstanding</span><strong className="redText">₹{account.summary.outstanding.toLocaleString('en-IN')}</strong></div></div>{account.ledgerEntries.length>0&&<section className="panel advancePanel"><div className="sectionHeading"><div><h2>Advance credit</h2><p>Available for adjustment against future invoices.</p></div></div><div className="paymentHistory">{account.ledgerEntries.map(entry=><div key={entry.id}><span><strong>{entry.referenceId||'ADVANCE'}</strong><small>{new Intl.DateTimeFormat('en-IN',{dateStyle:'medium'}).format(new Date(entry.occurredAt))} · {entry.description}</small></span><strong className="greenText">₹{Number(entry.amount).toLocaleString('en-IN')}</strong></div>)}</div></section>}<section className="feeLedger">{account.fees.map(fee=><article className="panel feeLedgerCard" key={fee.id}><div><div><span className="mono">{fee.invoiceNo||'INVOICE'}</span><h2>{fee.title}</h2><p>Due {new Intl.DateTimeFormat('en-IN',{dateStyle:'long'}).format(new Date(fee.dueDate))}</p></div><a href={`/api/proxy/fees/${fee.id}/invoice.pdf`}><DocumentArrowDownIcon/>Download PDF</a></div><dl><div><dt>Billed</dt><dd>₹{Number(fee.amount).toLocaleString('en-IN')}</dd></div><div><dt>Paid</dt><dd>₹{Number(fee.paidAmount).toLocaleString('en-IN')}</dd></div><div><dt>Outstanding</dt><dd>₹{fee.outstanding.toLocaleString('en-IN')}</dd></div><div><dt>Status</dt><dd><span className={`status ${fee.status==='PAID'?'present':'late'}`}>{fee.status}</span></dd></div></dl><div className="paymentHistory"><h3>Payment history</h3>{fee.payments.length?fee.payments.map(payment=><div key={payment.id}><span><strong>{payment.receiptNo}</strong><small>{new Intl.DateTimeFormat('en-IN',{dateStyle:'medium'}).format(new Date(payment.paidAt))} · {payment.method}</small></span><strong>₹{Number(payment.amount).toLocaleString('en-IN')}</strong></div>):<p>No payments collected for this invoice.</p>}</div></article>)}</section></>;
}
