'use client';

import { FormEvent, useState } from 'react';
import { ArrowDownTrayIcon, ArrowUpTrayIcon, CheckCircleIcon, XMarkIcon } from '@heroicons/react/24/outline';

type PreviewRow={row:number;errors:string[];admissionNo?:string;firstName?:string;lastName?:string;className?:string;section?:string;fatherName?:string};
type Preview={total:number;valid:number;invalid:number;rows:PreviewRow[]};

export function StudentImportDialog({onClose,onImported}:{onClose:()=>void;onImported:()=>Promise<void>}){
  const[file,setFile]=useState<File|null>(null);const[preview,setPreview]=useState<Preview|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[result,setResult]=useState<{imported:number;failed:number;classesCreated:number}|null>(null);
  async function upload(previewOnly:boolean){if(!file)return;setLoading(true);setError('');const body=new FormData();body.append('file',file);const response=await fetch(`/api/proxy/students-import${previewOnly?'?preview=true':''}`,{method:'POST',body});const data=await response.json().catch(()=>({}));setLoading(false);if(!response.ok){setError(data.message||'The Excel file could not be processed.');if(data.rows)setPreview({total:data.rows.length,valid:0,invalid:data.rows.length,rows:data.rows});return}if(previewOnly){setPreview(data);setResult(null)}else{setResult(data);setPreview(null);await onImported()}}
  function choose(event:FormEvent<HTMLInputElement>){const selected=(event.currentTarget.files||[])[0]||null;setFile(selected);setPreview(null);setResult(null);setError('')}
  return <div className="dialogBackdrop" onMouseDown={onClose}><div className="facilityDialog studentImportDialog" role="dialog" aria-modal="true" onMouseDown={event=>event.stopPropagation()}><div className="dialogTitle"><div><h2>Import students from Excel</h2><p>Validate the workbook first. New class and optional section combinations will be created automatically.</p></div><button onClick={onClose} aria-label="Close"><XMarkIcon/></button></div><div className="studentImportBody"><a className="templateDownload" href="/api/proxy/students-import/template"><ArrowDownTrayIcon/><span><strong>Download sample Excel template</strong><small>Includes required columns, a sample row, dropdowns, and formatting instructions.</small></span></a><label className="studentImportDrop"><ArrowUpTrayIcon/><strong>{file?file.name:'Choose completed Excel file'}</strong><small>.xlsx only · maximum 8 MB</small><input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={choose}/></label>{error&&<div className="loginError">{error}</div>}{preview&&<><div className="importSummary"><span><strong>{preview.total}</strong>Total rows</span><span><strong>{preview.valid}</strong>Ready</span><span className={preview.invalid?'hasErrors':''}><strong>{preview.invalid}</strong>Need correction</span></div><div className="tableWrap importPreview"><table><thead><tr><th>Excel row</th><th>Student</th><th>Admission no.</th><th>Class</th><th>Father</th><th>Validation</th></tr></thead><tbody>{preview.rows.slice(0,100).map(row=><tr key={row.row}><td>{row.row}</td><td><strong>{row.firstName} {row.lastName}</strong></td><td>{row.admissionNo||'Auto-generate'}</td><td>{row.className}{row.section?`-${row.section}`:''}</td><td>{row.fatherName||'—'}</td><td>{row.errors.length?<span className="importError">{row.errors.join(' · ')}</span>:<span className="importReady"><CheckCircleIcon/>Ready</span>}</td></tr>)}</tbody></table></div>{preview.rows.length>100&&<p className="importFootnote">Showing the first 100 of {preview.rows.length} rows.</p>}</>}{result&&<div className="importComplete"><CheckCircleIcon/><div><strong>{result.imported} students imported</strong><p>{result.classesCreated} new class/section records created{result.failed?` · ${result.failed} rows failed`:''}.</p></div></div>}<div className="dialogButtons"><button type="button" onClick={onClose}>{result?'Close':'Cancel'}</button>{!result&&<button type="button" disabled={!file||loading} onClick={()=>void upload(true)}>{loading?'Checking…':'Validate & preview'}</button>}{preview&&preview.invalid===0&&!result&&<button className="primary" disabled={loading} onClick={()=>void upload(false)}>{loading?'Importing…':`Import ${preview.valid} students`}</button>}</div></div></div></div>;
}
