'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { CalendarDaysIcon, CheckCircleIcon, ClockIcon, PlusIcon, XCircleIcon, XMarkIcon } from '@heroicons/react/24/outline';
import { useAuth } from './auth-provider';

type Child={id:string;admissionNo:string;firstName:string;lastName:string;class?:{name:string;section:string}};
type Leave={id:string;studentId:string;startDate:string;endDate:string;issue:string;details?:string;status:string;reviewNote?:string;createdAt:string;student:Child};
const issueLabels:Record<string,string>={FEVER:'Fever',HEADACHE:'Headache',COLD_AND_COUGH:'Cold and cough',STOMACH_PAIN:'Stomach pain',VOMITING:'Vomiting',DIARRHOEA:'Diarrhoea',BACK_PAIN:'Back pain',TOOTHACHE:'Toothache',EYE_INFECTION:'Eye infection',EAR_PAIN:'Ear pain',SKIN_ALLERGY:'Skin allergy',MINOR_INJURY:'Minor injury',DOCTOR_APPOINTMENT:'Doctor appointment',FAMILY_EMERGENCY:'Family emergency',RELIGIOUS_FUNCTION:'Religious function',OUT_OF_STATION:'Out of station',OTHER:'Other'};
const classLabel=(item?:{name:string;section:string})=>item?`${item.name}${item.section?`-${item.section}`:''}`:'Unassigned';
const today=()=>new Date().toISOString().slice(0,10);

export function StudentLeaveManager(){
  const{user}=useAuth();const parent=user?.role==='PARENT';const[leaves,setLeaves]=useState<Leave[]>([]);const[children,setChildren]=useState<Child[]>([]);const[issues,setIssues]=useState<string[]>(Object.keys(issueLabels));const[open,setOpen]=useState(false);const[message,setMessage]=useState('');
  const load=useCallback(async()=>{const response=await fetch('/api/proxy/modules/student-leave',{cache:'no-store'});if(response.ok)setLeaves(await response.json())},[]);
  useEffect(()=>{void load();if(parent)fetch('/api/proxy/modules/student-leave/context',{cache:'no-store'}).then(response=>response.ok?response.json():{children:[],issues:[]}).then(data=>{setChildren(data.children);setIssues(data.issues)})},[load,parent]);
  const pending=leaves.filter(item=>item.status==='PENDING').length,approved=leaves.filter(item=>item.status==='APPROVED').length,rejected=leaves.filter(item=>item.status==='REJECTED').length;
  async function review(id:string,status:'APPROVED'|'REJECTED'){const reviewNote=window.prompt(status==='APPROVED'?'Approval note (optional)':'Reason for rejection (optional)')||undefined;const response=await fetch(`/api/proxy/modules/student-leave/${id}/review`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,reviewNote})});const data=await response.json().catch(()=>({}));setMessage(response.ok?`Leave request ${status.toLowerCase()}.`:data.message||'Request could not be reviewed.');if(response.ok)await load()}
  async function cancel(id:string){const response=await fetch(`/api/proxy/modules/student-leave/${id}/cancel`,{method:'PATCH'});if(response.ok){setMessage('Leave request cancelled.');await load()}}
  return <><div className="pageHead"><div><h1>Student leave management</h1><p>{parent?'Apply for leave for any linked child and track the school decision.':'Review student leave requests for the classes available to your account.'}</p></div>{parent&&<button className="primary" onClick={()=>setOpen(true)} disabled={!children.length}><PlusIcon/>Apply for leave</button>}</div>
  <section className="leaveMetrics"><div><ClockIcon/><span><strong>{pending}</strong>Pending</span></div><div><CheckCircleIcon/><span><strong>{approved}</strong>Approved</span></div><div><XCircleIcon/><span><strong>{rejected}</strong>Rejected</span></div><div><CalendarDaysIcon/><span><strong>{leaves.length}</strong>Total requests</span></div></section>
  {message&&<div className="attendanceSuccess">{message}</div>}
  <section className="panel studentLeaveTable"><div className="sectionHeading"><div><h2>{parent?'My children’s leave requests':'Leave review queue'}</h2><p>Requests are retained as an audit-ready history.</p></div></div><div className="tableWrap"><table><thead><tr><th>Student</th><th>Dates</th><th>Duration</th><th>Reason</th><th>Details</th><th>Status</th><th>Action</th></tr></thead><tbody>{leaves.length?leaves.map(item=>{const days=Math.ceil((new Date(item.endDate).getTime()-new Date(item.startDate).getTime())/864e5)+1;return <tr key={item.id}><td><strong>{item.student.firstName} {item.student.lastName}</strong><small className="cellSubtext">{item.student.admissionNo} · {classLabel(item.student.class)}</small></td><td>{new Intl.DateTimeFormat('en-IN',{dateStyle:'medium'}).format(new Date(item.startDate))} – {new Intl.DateTimeFormat('en-IN',{dateStyle:'medium'}).format(new Date(item.endDate))}</td><td>{days} day{days===1?'':'s'}</td><td><strong>{issueLabels[item.issue]||item.issue}</strong></td><td>{item.details||'—'}{item.reviewNote&&<small className="cellSubtext">School: {item.reviewNote}</small>}</td><td><span className={`status ${item.status==='APPROVED'?'present':item.status==='REJECTED'||item.status==='CANCELLED'?'absent':'late'}`}>{item.status}</span></td><td>{parent?<button className="leaveCancel" disabled={item.status!=='PENDING'} onClick={()=>void cancel(item.id)}>Cancel</button>:<div className="reviewActions"><button disabled={item.status!=='PENDING'} onClick={()=>void review(item.id,'APPROVED')}>Approve</button><button disabled={item.status!=='PENDING'} onClick={()=>void review(item.id,'REJECTED')}>Reject</button></div>}</td></tr>}):<tr><td colSpan={7}><div className="tableState">No student leave requests yet.</div></td></tr>}</tbody></table></div></section>
  {open&&<LeaveRequestDialog children={children} issues={issues} onClose={()=>setOpen(false)} onSaved={async()=>{setOpen(false);setMessage('Leave request submitted for school review.');await load()}}/>}</>;
}

function LeaveRequestDialog({children,issues,onClose,onSaved}:{children:Child[];issues:string[];onClose:()=>void;onSaved:()=>Promise<void>}){
  const[issue,setIssue]=useState('FEVER');const[error,setError]=useState('');const[saving,setSaving]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError('');const form=new FormData(event.currentTarget);const response=await fetch('/api/proxy/modules/student-leave',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(form.entries()))});const data=await response.json().catch(()=>({}));if(!response.ok){setError(data.message||'Leave request could not be submitted.');setSaving(false);return}await onSaved()}
  return <div className="dialogBackdrop" onMouseDown={onClose}><div className="facilityDialog studentLeaveDialog" onMouseDown={event=>event.stopPropagation()}><div className="dialogTitle"><div><h2>Apply for student leave</h2><p>Choose a common reason. Add details only when the school needs more context.</p></div><button onClick={onClose}><XMarkIcon/></button></div><form className="facilityForm" onSubmit={submit}><label>Child<select name="studentId" required><option value="">Select child</option>{children.map(child=><option value={child.id} key={child.id}>{child.firstName} {child.lastName} · {child.admissionNo} · {classLabel(child.class)}</option>)}</select></label><div className="formColumns"><label>From<input name="startDate" type="date" min={today()} required/></label><label>To<input name="endDate" type="date" min={today()} required/></label></div><label>Reason<select name="issue" value={issue} onChange={event=>setIssue(event.target.value)}>{issues.map(value=><option value={value} key={value}>{issueLabels[value]||value}</option>)}</select></label><label>{issue==='OTHER'?'Please describe the reason':'Additional note (optional)'}<textarea name="details" rows={3} required={issue==='OTHER'} placeholder={issue==='OTHER'?'Enter the leave reason':'Symptoms, doctor advice, or any detail the teacher should know'}/></label>{error&&<div className="loginError">{error}</div>}<div className="dialogButtons"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving?'Submitting…':'Submit leave request'}</button></div></form></div></div>;
}
