'use client';
import { FormEvent, useEffect, useState } from 'react';
import { MapPinIcon, PlusIcon, TruckIcon, UserGroupIcon, XMarkIcon } from '@heroicons/react/24/outline';
import { useAuth } from './auth-provider';

type Vehicle={id:string;vehicleNo:string;registrationNo:string;type:'BUS'|'VAN';capacity:number;driverName:string;driverPhone:string;attendantName?:string;attendantPhone?:string;status:string;notes?:string;routes:{id:string;name:string}[]};
type Stop={id:string;name:string;sequence:number;pickupTime?:string;dropTime?:string;landmark?:string};
type Student={id:string;admissionNo:string;firstName:string;lastName:string;class?:{name:string;section?:string};transportAssignment?:Assignment|null};
type Assignment={id:string;studentId:string;routeId:string;stopId?:string;status:string;student:Student;stop?:Stop;route?:Route};
type Route={id:string;code:string;name:string;vehicleId?:string;vehicle?:Vehicle;morningStart?:string;afternoonStart?:string;status:string;notes?:string;stops:Stop[];assignments:Assignment[]};
type AdminData={role:'ADMIN';vehicles:Vehicle[];routes:Route[];summary:{vehicles:number;buses:number;vans:number;activeRoutes:number;assignedStudents:number;availableSeats:number}};
type FamilyStudent=Omit<Student,'transportAssignment'>&{transportAssignment?:Assignment&{route:Route}|null};
type FamilyData={role:'PARENT'|'STUDENT';students:FamilyStudent[]};
const api='/api/proxy/modules/transport';
const classLabel=(student:Student)=>student.class?`${student.class.name}${student.class.section?`-${student.class.section}`:''}`:'Class not assigned';

export function TransportManager(){
  const{user}=useAuth();const[data,setData]=useState<AdminData|FamilyData|null>(null);const[tab,setTab]=useState<'fleet'|'routes'|'students'>('fleet');const[dialog,setDialog]=useState<'vehicle'|'route'|'assign'|null>(null);const[editingVehicle,setEditingVehicle]=useState<Vehicle|null>(null);const[selectedRoute,setSelectedRoute]=useState<Route|null>(null);const[query,setQuery]=useState('');const[students,setStudents]=useState<Student[]>([]);const[selectedStudent,setSelectedStudent]=useState<Student|null>(null);const[routeId,setRouteId]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);
  async function load(){const response=await fetch(api,{cache:'no-store'});if(response.ok)setData(await response.json())}
  useEffect(()=>{void load()},[]);
  useEffect(()=>{if(user?.role!=='ADMIN'||query.trim().length<2){setStudents([]);return}const timer=window.setTimeout(()=>fetch(`${api}/students?q=${encodeURIComponent(query.trim())}`,{cache:'no-store'}).then(r=>r.ok?r.json():[]).then(setStudents),250);return()=>clearTimeout(timer)},[query,user?.role]);
  const admin=data?.role==='ADMIN'?data:null;const routes=admin?.routes??[];const chosenRoute=routes.find(item=>item.id===routeId);
  function close(){setDialog(null);setEditingVehicle(null);setSelectedRoute(null);setSelectedStudent(null);setError('');setQuery('');setStudents([]);setRouteId('')}
  async function send(url:string,method:string,body?:unknown){setBusy(true);setError('');const response=await fetch(url,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const result=await response.json().catch(()=>({}));if(!response.ok){setError(result.message||'The change could not be saved.');setBusy(false);return false}await load();setBusy(false);return true}
  async function saveVehicle(event:FormEvent<HTMLFormElement>){event.preventDefault();const body=Object.fromEntries(new FormData(event.currentTarget));if(await send(editingVehicle?`${api}/vehicles/${editingVehicle.id}`:`${api}/vehicles`,editingVehicle?'PUT':'POST',body))close()}
  async function saveRoute(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const stops=String(form.get('stops')||'').split('\n').map(line=>line.trim()).filter(Boolean).map(line=>{const[name,pickupTime,dropTime,landmark]=line.split('|').map(value=>value.trim());return{name,pickupTime,dropTime,landmark}});const body={code:form.get('code'),name:form.get('name'),vehicleId:form.get('vehicleId'),morningStart:form.get('morningStart'),afternoonStart:form.get('afternoonStart'),status:form.get('status'),notes:form.get('notes'),stops};if(await send(`${api}/routes`,'POST',body))close()}
  async function addStop(event:FormEvent<HTMLFormElement>){event.preventDefault();if(selectedRoute&&await send(`${api}/routes/${selectedRoute.id}/stops`,'POST',Object.fromEntries(new FormData(event.currentTarget))))close()}
  async function assign(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selectedStudent)return setError('Search for and select a student first.');const body=Object.fromEntries(new FormData(event.currentTarget));if(await send(`${api}/assignments`,'POST',{...body,studentId:selectedStudent.id}))close()}
  if(!data)return <div className="authLoading"><div className="authSpinner"/><span>Loading transport…</span></div>;
  if(data.role!=='ADMIN')return <FamilyTransport students={data.students}/>;
  return <><div className="pageHead transportHead"><div><h1>Transport</h1><p>Manage the school fleet, routes, stops, and student travel assignments.</p></div><button className="primary" onClick={()=>setDialog('assign')}><UserGroupIcon/>Assign student</button></div>
    <section className="transportMetrics">
      <div><TruckIcon/><span>Fleet<strong>{admin!.summary.vehicles}</strong><small>{admin!.summary.buses} buses · {admin!.summary.vans} vans</small></span></div>
      <div><MapPinIcon/><span>Active routes<strong>{admin!.summary.activeRoutes}</strong><small>Morning and return journeys</small></span></div>
      <div><UserGroupIcon/><span>Assigned students<strong>{admin!.summary.assignedStudents}</strong><small>Current active assignments</small></span></div>
      <div><TruckIcon/><span>Seats available<strong>{admin!.summary.availableSeats}</strong><small>Across active routes</small></span></div>
    </section>
    <section className="panel transportPanel"><div className="transportTabs"><button className={tab==='fleet'?'active':''} onClick={()=>setTab('fleet')}>Fleet</button><button className={tab==='routes'?'active':''} onClick={()=>setTab('routes')}>Routes & stops</button><button className={tab==='students'?'active':''} onClick={()=>setTab('students')}>Student assignments</button></div>
      {tab==='fleet'&&<><div className="transportToolbar"><div><h2>Vehicles</h2><p>Driver and attendant contacts are visible only to assigned families.</p></div><button className="primary" onClick={()=>setDialog('vehicle')}><PlusIcon/>Add vehicle</button></div><div className="fleetGrid">{admin!.vehicles.length?admin!.vehicles.map(vehicle=><article className="vehicleCard" key={vehicle.id}><div className="vehicleCardTop"><span className={`vehicleGlyph ${vehicle.type.toLowerCase()}`}><TruckIcon/></span><i className={`transportStatus ${vehicle.status.toLowerCase()}`}>{vehicle.status}</i></div><h3>{vehicle.vehicleNo}</h3><p>{vehicle.type} · {vehicle.registrationNo}</p><dl><div><dt>Capacity</dt><dd>{vehicle.capacity} seats</dd></div><div><dt>Driver</dt><dd>{vehicle.driverName} · {vehicle.driverPhone}</dd></div><div><dt>Attendant</dt><dd>{vehicle.attendantName?`${vehicle.attendantName}${vehicle.attendantPhone?` · ${vehicle.attendantPhone}`:''}`:'Not assigned'}</dd></div><div><dt>Routes</dt><dd>{vehicle.routes.map(route=>route.name).join(', ')||'Not allocated'}</dd></div></dl><button className="textButton" onClick={()=>{setEditingVehicle(vehicle);setDialog('vehicle')}}>Edit vehicle</button></article>):<Empty text="No vehicles have been added yet."/>}</div></>}
      {tab==='routes'&&<><div className="transportToolbar"><div><h2>Routes and stops</h2><p>Pickup and return timings are shared with assigned students and parents.</p></div><button className="primary" onClick={()=>setDialog('route')}><PlusIcon/>Create route</button></div><div className="routeList">{routes.length?routes.map(route=><article className="routeCard" key={route.id}><div className="routeSummary"><span><strong>{route.code} · {route.name}</strong><small>{route.vehicle?`${route.vehicle.vehicleNo} · ${route.vehicle.type}`:'Vehicle not assigned'} · {route.assignments.length}/{route.vehicle?.capacity??0} students</small></span><i className={`transportStatus ${route.status.toLowerCase()}`}>{route.status}</i></div><div className="stopTrack">{route.stops.map(stop=><div key={stop.id}><i/><span><strong>{stop.sequence}. {stop.name}</strong><small>Pickup {stop.pickupTime||'—'} · Return {stop.dropTime||'—'}{stop.landmark?` · ${stop.landmark}`:''}</small></span><button aria-label={`Delete ${stop.name}`} onClick={()=>void send(`${api}/stops/${stop.id}`,'DELETE')}><XMarkIcon/></button></div>)}</div><button className="textButton" onClick={()=>{setSelectedRoute(route);setDialog('route')}}><PlusIcon/>Add another stop</button></article>):<Empty text="Create the first route and its pickup stops."/>}</div></>}
      {tab==='students'&&<><div className="transportToolbar"><div><h2>Current student assignments</h2><p>Reassigning a student automatically replaces their previous route.</p></div><button className="primary" onClick={()=>setDialog('assign')}><PlusIcon/>Assign student</button></div><div className="tableWrap"><table><thead><tr><th>Student</th><th>Class</th><th>Route</th><th>Vehicle</th><th>Stop</th><th>Pickup</th><th>Action</th></tr></thead><tbody>{routes.flatMap(route=>route.assignments.map(item=><tr key={item.id}><td><strong>{item.student.firstName} {item.student.lastName}</strong><br/><span className="mono">{item.student.admissionNo}</span></td><td>{classLabel(item.student)}</td><td>{route.code} · {route.name}</td><td>{route.vehicle?.vehicleNo||'—'}</td><td>{item.stop?.name||'Not selected'}</td><td>{item.stop?.pickupTime||'—'}</td><td><button className="textButton danger" onClick={()=>void send(`${api}/assignments/${item.id}/end`,'PATCH')}>End assignment</button></td></tr>))}{admin!.summary.assignedStudents===0&&<tr><td colSpan={7} className="transportEmpty">No students are assigned yet.</td></tr>}</tbody></table></div></>}
    </section>
    {dialog==='vehicle'&&<Modal title={editingVehicle?'Edit vehicle':'Add vehicle'} subtitle="Record operational and contact details." onClose={close}><form className="facilityForm" onSubmit={saveVehicle}><div className="formColumns"><label>School vehicle number<input name="vehicleNo" defaultValue={editingVehicle?.vehicleNo} placeholder="BUS-01" required/></label><label>Registration number<input name="registrationNo" defaultValue={editingVehicle?.registrationNo} placeholder="HR-00-AB-1234" required/></label></div><div className="formColumns"><label>Vehicle type<select name="type" defaultValue={editingVehicle?.type||'BUS'}><option>BUS</option><option>VAN</option></select></label><label>Seating capacity<input name="capacity" type="number" min="1" max="100" defaultValue={editingVehicle?.capacity||40} required/></label></div><div className="formColumns"><label>Driver name<input name="driverName" defaultValue={editingVehicle?.driverName} required/></label><label>Driver phone<input name="driverPhone" inputMode="tel" defaultValue={editingVehicle?.driverPhone} required/></label></div><div className="formColumns"><label>Attendant name<input name="attendantName" defaultValue={editingVehicle?.attendantName}/></label><label>Attendant phone<input name="attendantPhone" inputMode="tel" defaultValue={editingVehicle?.attendantPhone}/></label></div><label>Status<select name="status" defaultValue={editingVehicle?.status||'ACTIVE'}><option>ACTIVE</option><option>MAINTENANCE</option><option>INACTIVE</option></select></label><label>Internal note<textarea name="notes" rows={2} defaultValue={editingVehicle?.notes}/></label><FormEnd error={error} busy={busy} onClose={close} label="Save vehicle"/></form></Modal>}
    {dialog==='route'&&!selectedRoute&&<Modal title="Create route" subtitle="Enter one stop per line: Name | pickup | return | landmark." onClose={close}><form className="facilityForm" onSubmit={saveRoute}><div className="formColumns"><label>Route code<input name="code" placeholder="RT-01" required/></label><label>Route name<input name="name" placeholder="City Centre Route" required/></label></div><label>Vehicle<select name="vehicleId"><option value="">Assign later</option>{admin!.vehicles.filter(v=>v.status==='ACTIVE').map(v=><option value={v.id} key={v.id}>{v.vehicleNo} · {v.type} · {v.capacity} seats</option>)}</select></label><div className="formColumns"><label>Morning departure<input name="morningStart" type="time"/></label><label>School departure<input name="afternoonStart" type="time"/></label></div><label>Stops<textarea name="stops" rows={6} required placeholder={'Main Chowk | 07:10 | 15:10 | Near post office\\nSector 4 | 07:20 | 15:00 | Community centre'}/></label><input type="hidden" name="status" value="ACTIVE"/><label>Internal note<textarea name="notes" rows={2}/></label><FormEnd error={error} busy={busy} onClose={close} label="Create route"/></form></Modal>}
    {dialog==='route'&&selectedRoute&&<Modal title={`Add stop to ${selectedRoute.name}`} subtitle="The stop will be appended to the route in sequence." onClose={close}><form className="facilityForm" onSubmit={addStop}><label>Stop name<input name="name" required/></label><div className="formColumns"><label>Pickup time<input name="pickupTime" type="time"/></label><label>Return time<input name="dropTime" type="time"/></label></div><label>Landmark<input name="landmark"/></label><FormEnd error={error} busy={busy} onClose={close} label="Add stop"/></form></Modal>}
    {dialog==='assign'&&<Modal title="Assign student transport" subtitle="Search by name, admission number, or guardian mobile." onClose={close}><form className="facilityForm" onSubmit={assign}><label>Find student<input value={query} onChange={event=>{setQuery(event.target.value);setSelectedStudent(null)}} placeholder="Type at least 2 characters"/></label>{students.length>0&&!selectedStudent&&<div className="studentSearchResults">{students.map(student=><button type="button" onClick={()=>{setSelectedStudent(student);setQuery(`${student.firstName} ${student.lastName}`)}} key={student.id}><strong>{student.firstName} {student.lastName}</strong><span>{student.admissionNo} · {classLabel(student)}{student.transportAssignment?` · Currently ${student.transportAssignment.route?.name}`:''}</span></button>)}</div>}{selectedStudent&&<div className="selectedTransportStudent"><UserGroupIcon/><span><strong>{selectedStudent.firstName} {selectedStudent.lastName}</strong><small>{selectedStudent.admissionNo} · {classLabel(selectedStudent)}</small></span></div>}<label>Route<select name="routeId" value={routeId} onChange={event=>setRouteId(event.target.value)} required><option value="">Select active route</option>{routes.filter(r=>r.status==='ACTIVE'&&r.vehicle?.status==='ACTIVE').map(r=><option value={r.id} key={r.id}>{r.code} · {r.name} · {Math.max(0,(r.vehicle?.capacity??0)-r.assignments.length)} seats left</option>)}</select></label><label>Pickup stop<select name="stopId" disabled={!chosenRoute}><option value="">Select stop</option>{chosenRoute?.stops.map(stop=><option value={stop.id} key={stop.id}>{stop.name} · {stop.pickupTime||'Time not set'}</option>)}</select></label><label>Effective from<input name="effectiveFrom" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Note<textarea name="notes" rows={2}/></label><FormEnd error={error} busy={busy} onClose={close} label="Assign transport"/></form></Modal>}
  </>;
}
function FamilyTransport({students}:{students:FamilyStudent[]}){return <><div className="pageHead"><div><h1>School transport</h1><p>Current route, pickup stop, timings, and authorized transport contacts.</p></div></div><div className="familyTransportGrid">{students.map(student=>{const assignment=student.transportAssignment;const route=assignment?.route;const stop=assignment?.stop;return <article className="familyTransportCard" key={student.id}><div className="familyStudent"><span>{student.firstName[0]}{student.lastName[0]}</span><div><h2>{student.firstName} {student.lastName}</h2><p>{student.admissionNo} · {classLabel(student as Student)}</p></div></div>{assignment?.status==='ACTIVE'&&route?<><div className="familyRouteHero"><TruckIcon/><span><small>{route.vehicle?.type||'School vehicle'}</small><strong>{route.vehicle?.vehicleNo||'Vehicle being assigned'}</strong><em>{route.code} · {route.name}</em></span></div><dl><div><dt>Pickup stop</dt><dd>{stop?.name||'Contact transport office'}</dd></div><div><dt>Pickup time</dt><dd>{stop?.pickupTime||'—'}</dd></div><div><dt>Return time</dt><dd>{stop?.dropTime||'—'}</dd></div><div><dt>Landmark</dt><dd>{stop?.landmark||'—'}</dd></div><div><dt>Driver</dt><dd>{route.vehicle?`${route.vehicle.driverName} · ${route.vehicle.driverPhone}`:'—'}</dd></div><div><dt>Attendant</dt><dd>{route.vehicle?.attendantName?`${route.vehicle.attendantName}${route.vehicle.attendantPhone?` · ${route.vehicle.attendantPhone}`:''}`:'—'}</dd></div></dl><p className="trackingFuture">Live tracking is not enabled. The transport record is ready to support it later without changing your assignment.</p></>:<div className="transportUnassigned"><MapPinIcon/><strong>Transport not assigned</strong><span>Contact the school office if this student should use school transport.</span></div>}</article>})}{students.length===0&&<Empty text="No linked students were found."/>}</div></>}
function Modal({title,subtitle,onClose,children}:{title:string;subtitle:string;onClose:()=>void;children:React.ReactNode}){return <div className="dialogBackdrop" onMouseDown={onClose}><div className="facilityDialog transportDialog" onMouseDown={event=>event.stopPropagation()}><div className="dialogTitle"><div><h2>{title}</h2><p>{subtitle}</p></div><button onClick={onClose}><XMarkIcon/></button></div>{children}</div></div>}
function FormEnd({error,busy,onClose,label}:{error:string;busy:boolean;onClose:()=>void;label:string}){return <>{error&&<div className="loginError">{error}</div>}<div className="dialogButtons"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':label}</button></div></>}
function Empty({text}:{text:string}){return <div className="transportEmpty"><TruckIcon/><span>{text}</span></div>}
